services:
  db:
    image: postgres:16
    container_name: spendsense_db
    environment:
      POSTGRES_USER: spendsense
      POSTGRES_PASSWORD: spendsense
      POSTGRES_DB: spendsense
    ports:
      - "5432:5432"
    volumes:
      - spendsense_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spendsense -d spendsense"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spendsense_backend
    env_file:
      - ./backend/.env
    environment:
      # override DB to use docker db
      DATABASE_URL: postgresql+psycopg://spendsense:spendsense@db:5432/spendsense
      CORS_ORIGINS: http://localhost:3000
      ENVIRONMENT: local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spendsense_frontend
    env_file:
      - ./frontend/.env.local
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  spendsense_pgdata:
